[pyprland]
plugins = [ "scratchpads" ]

[scratchpads.yazi]
command = "kitty --class yazi-scratchpad yazi"
class = "yazi-scratchpad"
size = "40% 35%"
animation = "fromBottom"

[scratchpads.ncspot]
command = "kitty --class ncspot-scratchpad ncspot"
class = "ncspot-scratchpad"
size = "30% 20%"
animation = "fromBottom"
lazy = true
